#!/usr/bin/env ruby

require 'yaml'
require 'rubygems'
require 'trollop'
require 'mechanize'

config_default = File.expand_path '~/.config/whatcdsearch'

opts = Trollop::options do
  banner <<-END_BANNER
Searches for a music torrent in What.CD, by author and album.

Example:
  whatcdsearch -a "Talking Heads" -l "Live USA"

Arguments:
END_BANNER

  opt :artist, 'Artist name', :type => String, :required => true
  opt :album, 'Album name', :type => String, :required => true
  opt :username, 'What.CD username (looks in config if not specified)',
      :type => String
  opt :password, 'What.CD password (looks in config if not specified)',
      :type => String
  opt :config, "Location of configuration file (defaults to #{config_default})",
      :type => String, :default => config_default
end

unless opts[:username] and opts[:password]
  unless File.exists?(opts[:config])
    Trollop::die :config, "file #{opts[:config]} must exist"
  end
  config = YAML::load File.open(opts[:config])
  Trollop::die :config, 'must specify username' unless config['username']
  opts[:username] = config['username']
  Trollop::die :config, 'must specify password' unless config['password']
  opts[:password] = config['password']
end

mech = Mechanize.new
# Click login link
login_page = mech.get 'http://what.cd/login.php'
# Submit login page
home_page = login_page.form_with(:action => 'login.php') do |form|
    form.username = opts[:username]
    form.password = opts[:password]
end.submit
# Get to the search page
search_page = mech.get 'http://what.cd/torrents.php?action=advanced&'
# Search
results_page = search_page.form_with(:name => 'filter') do |form|
    form.artistname = opts[:artist]
    form.groupname = opts[:album]
    form.order_by = 'snatched'
end.submit
# Get the links on the results page
links = results_page.links_with(
    :text => 'DL', :href => /^torrents\.php\?action=download/)

if links.any?
  puts 'http://what.cd/' + links[0].href
else
  $stderr.puts "No torrents found for #{opts[:artist]} - #{opts[:album]}."
  exit 1
end

